name: shelters
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #  STATE MANAGEMENT AND SL
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  get_it: ^7.2.0
  injectable: ^1.5.3

  #  NAVIGATION
  routemaster: ^1.0.1

  #  NETWORK
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.2
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1

  #  UTILS
  package_info_plus: ^8.0.0
  device_info: ^2.0.2
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^6.0.0
  intl: ^0.19.0
  dartz: ^0.10.1
  permission_handler: ^11.3.1
  url_launcher: ^6.0.20
  flutter_gen: ^5.4.0
  fluster: ^1.2.0
  collection: ^1.16.0
  geolocator: ^11.0.0
  map_launcher: ^3.3.0

  #  IMAGES
  flutter_svg: ^2.0.10+1

  # ICONS
  cupertino_icons: ^1.0.3

  # OTHER
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  flutter_gen_runner: ^5.4.0
  injectable_generator: ^1.5.4
  flutter_launcher_icons: ^0.11.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/markers/
